name: Chao Xing Auto Sign

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AutoSign
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SENDKEY: ${{ secrets.SENDKEY }}
          TGCHATID: ${{ secrets.TGCHATID }}
          BOTTOKEN: ${{ secrets.BOTTOKEN }}
          ADDRESS: ${{ secrets.ADDRESS }}
        run: python ./AutoSign.py
